CREATE TABLE category (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    image VARCHAR(200),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE blog (
    id SERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    coverImage VARCHAR(200),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    readCount INT DEFAULT 0,
    published BOOLEAN DEFAULT FALSE,
    featured BOOLEAN DEFAULT FALSE,
    writtenBy INT NOT NULL DEFAULT 22,
    FOREIGN KEY (writtenBy) REFERENCES users(id) ON DELETE CASCADE
  );

  //add new column published to blog table
  ALTER TABLE blog ADD COLUMN published BOOLEAN DEFAULT FALSE;
  ALTER TABLE blog ADD COLUMN readCount INT DEFAULT 0;
  ALTER TABLE blog ADD COLUMN featured BOOLEAN DEFAULT FALSE;
  ALTER TABLE blog ADD COLUMN writtenBy INT NOT NULL DEFAULT 22;



CREATE TABLE users (
id SERIAL NOT NULL PRIMARY KEY,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
name VARCHAR(100) NOT NULL,
role VARCHAR(100) NOT NULL DEFAULT 'user',
country VARCHAR(100),
profileImage VARCHAR(400),
verified BOOLEAN DEFAULT FALSE
);

ALTER TABLE users ADD COLUMN country VARCHAR(100);
ALTER TABLE users ADD COLUMN verified BOOLEAN DEFAULT FALSE;


CREATE TABLE blogcategories (
    id SERIAL NOT NULL PRIMARY KEY,
    blogId INT NOT NULL,
    categoryId INT NOT NULL,
    FOREIGN KEY (blogId) REFERENCES blog(id) ON DELETE CASCADE,
    FOREIGN KEY (categoryId) REFERENCES category(id) ON DELETE CASCADE
);


CREATE TABLE savedblog (
    id SERIAL NOT NULL PRIMARY KEY,
    userId INT NOT NULL,
    blogId INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (blogId) REFERENCES blog(id) ON DELETE CASCADE
);


CREATE TABLE messages (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    solved BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
